apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l807lu8x3-python
  janus-idp.io/tekton: l807lu8x3-python
  backstage.io/kubernetes-id: l807lu8x3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l807lu8x3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
