apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l807lu8x3-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l807lu8x3-python 
  name: l807lu8x3-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l807lu8x3-python 
