apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l807lu8x3-python 
  janus-idp.io/tekton: l807lu8x3-python
  backstage.io/kubernetes-id: l807lu8x3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l807lu8x3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml